version: '3'

services:

  # Host===================================================================
  framework_nginx:
    image: nginx:1.12
    container_name: framework_nginx
    ports:
      - 38080:80
    volumes:
      - ./src/:/var/www/html/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx/

  # App===================================================================
  framework_app:
    container_name: framework_app
    build: docker/app
    volumes:
      - ./src/:/var/www/html/
      - ./docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  # Database===================================================================
  framework_db:
    image: mysql:8.0
    container_name: framework_db
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - framework-db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  framework-db:
    driver: local

# windows環境で発生するnpm周りのエラー対策
#
#  node:
#    driver: local
